name: Copy Joe-Revised Theme from awbk to ceshi

# 触发条件：手动触发
on:
  workflow_dispatch:

# 权限设置
permissions:
  contents: write
  actions: read

jobs:
  copy-theme:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出源仓库（awbk）
      - name: Checkout source repository (awbk)
        uses: actions/checkout@v3
        with:
          repository: aw168/awbk
          path: source_awbk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 需要在 ceshi 仓库中配置名为 PERSONAL_ACCESS_TOKEN 的 Secret

      # 2. 检出目标仓库（ceshi）
      - name: Checkout target repository (ceshi)
        uses: actions/checkout@v3
        with:
          repository: aw168/ceshi
          path: target_ceshi
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 同样使用 ceshi 仓库中的 PERSONAL_ACCESS_TOKEN

      # 3. 复制 Joe-Revised 主题文件
      - name: Copy Joe-Revised theme files
        run: |
          # 创建目标目录（如果不存在）
          mkdir -p target_ceshi/usr/themes/Joe-Revised
          # 复制源仓库中 Joe-Revised 目录下的所有内容到目标仓库的 Joe-Revised 目录
          cp -r source_awbk/usr/themes/Joe-Revised/* target_ceshi/usr/themes/Joe-Revised/

      # 4. 提交更改到目标仓库（ceshi）
      - name: Commit and push changes to ceshi
        working-directory: target_ceshi
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add usr/themes/Joe-Revised
          git commit -m "Add Joe-Revised theme files from awbk"
          git push
