name: Unzip Typecho to Root

# 触发条件：手动触发或当推送包含 typecho.zip 文件时
on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: '要解压的 ZIP 文件名 (默认为 typecho.zip)'
        required: true
        default: 'typecho.zip'
  push:
    branches:
      - main # 当推送到 main 分支时触发
    paths:
      - 'typecho.zip' # 只有当推送包含 typecho.zip 文件时才触发

# 权限设置
permissions:
  contents: write
  actions: read

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 建议使用具有 write 权限的 Token

      # 2. 设置 up Python (用于 unzip 命令)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # 3. 安装 unzip 工具
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # 4. 解压文件到根目录
      - name: Unzip files to root
        run: unzip -o "${{ github.event.inputs.zip_filename }}" -d .

      # 5. 删除 ZIP 文件 (可选)
      - name: Remove zip file
        run: rm "${{ github.event.inputs.zip_filename }}"

      # 6. 配置 Git User
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 7. 添加和提交更改
      - name: Add and Commit Changes
        run: git add . && git commit -m "Unzip ${{ github.event.inputs.zip_filename }} files to root"

      # 8. 推送更改
      - name: Push Changes
        run: git push
